### ISSUE TITLE
Apple Silicon with UTM

### ISSUE THREAD

**Issue by senf666** [LinaYorda/OSINTko#2]
Tested on a MacBook Air M2 using UTM.

When attempting to install I get an error:

`The selected boot image contains the word 'amd64' but the guest architecture is 'ARM64 (aarch64)'. Please ensure you have selected an image that iscompatible with 'arm64'.`
<img width="272" alt="Screenshot 2024-04-14 at 17 10 55" src="https://github.com/LinaYorda/OSINTko/assets/3512672/65b81f28-4371-4a24-bf86-722665bc10c7">

maybe there is a specific way to run OSINTko with UTM and apple arm chips?

**Comment by senf666** [comment]
I figured it out. Have to select emulation and not Virtualization from UTM menu.

**Comment by LinaYorda** [comment]
Glad you had it running. Thank you for the info.
