### ISSUE TITLE
Credentials for Kali

### ISSUE THREAD

**Issue by 7h3pr0xy** [LinaYorda/OSINTko#3]
Hi team, 

Providing Kali ISO for osint is good but adding credentials to login will be better.

**Comment by LinaYorda** [comment]
Hey!
I'm not entirely sure, but do you mean the credentials for login after creating a machine? These would be the default user: kali and password: kali

**Comment by capslock303** [comment]
Hi Lina.  So, not sure why, but kali:kali isn't working.

**Comment by LinaYorda** [comment]
Hello, have you actually installed the ISO, or you have tried it on live boot?

**Comment by capslock303** [comment]
> Hello, have you actually installed the ISO, or you have tried it on live boot?

Yep, that was the issue - I hadn't installed the ISO, I was just running it live.  Thank you!
